
import static com.sun.source.util.DocTrees.instance;
import static javax.swing.JOptionPane.showMessageDialog;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Angel Gabriel
 */
public class Suma1aN extends javax.swing.JFrame {

    private static final String Res = "Resultado: ";
    private static final String TE = "Tiempo de ejecución: ";

    public static Suma1aN getInstance() {
        if (instance == null) {
            instance = new Suma1aN();
        }
        return instance;
    }

    /**
     * Creates new form Suma1aN
     */
    private Suma1aN() {
        initComponents();
        addWindowListener(VentanaPrincipal.escuchaHijo);
        collection = new XYSeriesCollection();
        series1 = new XYSeries("Sumatoria de 1 a N ");
        collection.addSeries(series1);
        series2 = new XYSeries("Sumatoria de 1 a N (Gauss) ");
        collection.addSeries(series2);
        series3 = new XYSeries("Sumatoria de 1 a N (Recursivo)");
        collection.addSeries(series3);
        jfc = ChartFactory.createXYLineChart("Coste de algoritmo", "Iteración", "Tiempo", collection,
                PlotOrientation.VERTICAL, true, false, false);
        ChartPanel oPanel = new ChartPanel(jfc);
        panel1.setLayout(new java.awt.BorderLayout());
        panel1.add(oPanel);
        panel1.validate();

    }//UNIT COMPONENTS

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnSuma1aN = new javax.swing.JButton();
        Gauss = new javax.swing.JButton();
        btnRecursivo = new javax.swing.JButton();
        lblRes = new javax.swing.JLabel();
        lblTS1 = new javax.swing.JLabel();
        lblTG = new javax.swing.JLabel();
        lblTr = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Numero: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        getContentPane().add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        getContentPane().add(txtNumero, gridBagConstraints);

        btnSuma1aN.setText("Suma1An");
        btnSuma1aN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuma1aNActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        getContentPane().add(btnSuma1aN, gridBagConstraints);

        Gauss.setText("Gauss");
        Gauss.setAutoscrolls(true);
        Gauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaussActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        getContentPane().add(Gauss, gridBagConstraints);

        btnRecursivo.setText("Recursividad");
        btnRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecursivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        getContentPane().add(btnRecursivo, gridBagConstraints);

        lblRes.setText("Resultado serie numerico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        getContentPane().add(lblRes, gridBagConstraints);

        lblTS1.setText("Tiempo suma 1aN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        getContentPane().add(lblTS1, gridBagConstraints);

        lblTG.setText("Tiempo Gauss");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        getContentPane().add(lblTG, gridBagConstraints);

        lblTr.setText("Tiempo Recursivo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.03;
        getContentPane().add(lblTr, gridBagConstraints);

        panel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(panel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private int extraerNum() throws Exception {
        int posicion;
        try {
            posicion = Integer.parseInt(txtNumero.getText());
            if (posicion < 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            throw new Exception("Inserta un número natural");
        }
        return posicion;
    }
    private void btnSuma1aNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuma1aNActionPerformed
        int n = 0;
        try {
            n = extraerNum();
        } catch (Exception e) {
            showMessageDialog(this, e.getMessage());
            return;
        }
        long tI = System.nanoTime();
        lblRes.setText(Res + suma1aN(n));
        lblTS1.setText(TE + (System.nanoTime() - tI));
        series1.clear();
        for (int i = 0; i < n; i++) {
            series1.add(i, 4 * i + 4);
        }
    }//GEN-LAST:event_btnSuma1aNActionPerformed

    private void GaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaussActionPerformed
        int n = 0;
        try {
            n = extraerNum();
        } catch (Exception e) {
            showMessageDialog(this, e.getMessage());
            return;
        }
        long tI = System.nanoTime();
        lblRes.setText(Res + suma1aNMGauss(n));
        lblTG.setText(TE + (System.nanoTime() - tI));
        series2.clear();
        for (int i = 0; i < n; i++) {
            series2.add(i, 3);
        }
    }//GEN-LAST:event_GaussActionPerformed

    private void btnRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursivoActionPerformed
        int n = 0;
        try {
            n = extraerNum();
        } catch (Exception e) {
            showMessageDialog(this, e.getMessage());
            return;
        }
        long tI = System.nanoTime();
        lblRes.setText(Res + suma1aNR(n));
        lblTr.setText(TE + (System.nanoTime() - tI));
        for (int i = 0,no = n-1; i < no; i++) {
            series3.add(i, 3 * i);
        }
    }//GEN-LAST:event_btnRecursivoActionPerformed
    
    public static int suma1aN(int n) {
        int s = 0; //1 
        //        1       (n+1)   n                  O(n)   t(n)=4n+4
        for (int i = 0; i <= n; i++) {
            s = s + i;//2n
        }
        return s;//1 
    }//suma1aN**********************************

    public static int suma1aNMGauss(int n) {
        //              1       1       1
        return (n * (n + 1) / 2);// 3
    }

    public static int suma1aNR(int n) { // 
        // y constante
        if (n == 1) {  //1
            return 1; //1
        } else {//                         
            return n + suma1aNR(n - 1); //1+n
        }
    }// *** 3n

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suma1aN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suma1aN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suma1aN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suma1aN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suma1aN().setVisible(true);
            }
        });
    }
    private static Suma1aN instance;
    private JFreeChart jfc;
    private XYSeriesCollection collection;
    private XYSeries series1;
    private XYSeries series2;
    private XYSeries series3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gauss;
    private javax.swing.JButton btnRecursivo;
    private javax.swing.JButton btnSuma1aN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblTG;
    private javax.swing.JLabel lblTS1;
    private javax.swing.JLabel lblTr;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
